export class RulesRequest {
    account: string;
    request_type: string;
    metatrader: string;
    bot_version: string;
    status: string;
    challenge_begins: string;
    challenge_ends: string;
    initial_balance: string;
    max_daily_loss: string;
    max_loss: string;
    profit_target: string;
    minimum_trading_days: string;
    trading_days: string;
    max_trading_days: string;
    phase: string;
    challenge_won: string;
    daily_kod: string;
    time_exceeded: string;
    challenge_extended: string;
    total_kod: string;
    max_daily_currency: string;
    max_daily_remaining: string;
    max_total_currency: string;
    max_total_remaining: string;
    balance: string;
    ea_date: string;
    ea_datetime: string;
    starting_daily_equity: string;
    extend_challenge: string;
    challenge_extra_days: string;
    profit_to_extend: string;
    consistency_kod:string;
    consistency_value:string;
  }